apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  labels:
    app: wallet-service
spec:
  type: ClusterIP
  selector:
    app: wallet-service
  ports:
    - port: 80
      targetPort: 8302
      protocol: TCP
